// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'d053400065dae9871597f6dd1fdfb5fe609f248abf79bc64e67885ff98e399a4'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Agent: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_utilisateur: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly Mouvement: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_vehicule: CodecTypes['pg/int4@1']['output'] | null;
      readonly heure_arrivee: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly heure_depart: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id_agent: CodecTypes['pg/int4@1']['output'] | null;
      readonly statut: 'sur_site' | 'hors_site' | null;
      readonly observation: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Personnel: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_utilisateur: CodecTypes['pg/int4@1']['output'] | null;
      readonly fonction: ReadonlyArray<'DGASJ' | 'DGCC' | 'DGCP'>;
    };
    readonly Utilisateur: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nom: CodecTypes['pg/text@1']['output'] | null;
      readonly prenom: CodecTypes['pg/text@1']['output'] | null;
      readonly matricule: CodecTypes['pg/text@1']['output'] | null;
      readonly mot_de_passe: CodecTypes['pg/text@1']['output'] | null;
      readonly role: ReadonlyArray<'agent' | 'admin' | 'superviseur'>;
      readonly est_actif: CodecTypes['pg/bool@1']['output'] | null;
    };
    readonly Vehicule: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly numero_plaque: CodecTypes['pg/text@1']['output'] | null;
      readonly id_personnel: CodecTypes['pg/int4@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Agent: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_utilisateur: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly Mouvement: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_vehicule: CodecTypes['pg/int4@1']['input'] | null;
      readonly heure_arrivee: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly heure_depart: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id_agent: CodecTypes['pg/int4@1']['input'] | null;
      readonly statut: 'sur_site' | 'hors_site' | null;
      readonly observation: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Personnel: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_utilisateur: CodecTypes['pg/int4@1']['input'] | null;
      readonly fonction: ReadonlyArray<'DGASJ' | 'DGCC' | 'DGCP'>;
    };
    readonly Utilisateur: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nom: CodecTypes['pg/text@1']['input'] | null;
      readonly prenom: CodecTypes['pg/text@1']['input'] | null;
      readonly matricule: CodecTypes['pg/text@1']['input'] | null;
      readonly mot_de_passe: CodecTypes['pg/text@1']['input'] | null;
      readonly role: ReadonlyArray<'agent' | 'admin' | 'superviseur'>;
      readonly est_actif: CodecTypes['pg/bool@1']['input'] | null;
    };
    readonly Vehicule: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly numero_plaque: CodecTypes['pg/text@1']['input'] | null;
      readonly id_personnel: CodecTypes['pg/int4@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly agent: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_utilisateur: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly mouvement: {
      readonly heure_arrivee: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly heure_depart: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_agent: CodecTypes['pg/int4@1']['output'] | null;
      readonly id_vehicule: CodecTypes['pg/int4@1']['output'] | null;
      readonly observation: CodecTypes['pg/text@1']['output'] | null;
      readonly statut: 'sur_site' | 'hors_site' | null;
    };
    readonly personnel: {
      readonly fonction: ReadonlyArray<'DGASJ' | 'DGCC' | 'DGCP'>;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_utilisateur: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly utilisateur: {
      readonly est_actif: CodecTypes['pg/bool@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly matricule: CodecTypes['pg/text@1']['output'] | null;
      readonly mot_de_passe: CodecTypes['pg/text@1']['output'] | null;
      readonly nom: CodecTypes['pg/text@1']['output'] | null;
      readonly prenom: CodecTypes['pg/text@1']['output'] | null;
      readonly role: ReadonlyArray<'agent' | 'admin' | 'superviseur'>;
    };
    readonly vehicule: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_personnel: CodecTypes['pg/int4@1']['output'] | null;
      readonly numero_plaque: CodecTypes['pg/text@1']['output'] | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly agent: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_utilisateur: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly mouvement: {
      readonly heure_arrivee: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly heure_depart: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_agent: CodecTypes['pg/int4@1']['input'] | null;
      readonly id_vehicule: CodecTypes['pg/int4@1']['input'] | null;
      readonly observation: CodecTypes['pg/text@1']['input'] | null;
      readonly statut: 'sur_site' | 'hors_site' | null;
    };
    readonly personnel: {
      readonly fonction: ReadonlyArray<'DGASJ' | 'DGCC' | 'DGCP'>;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_utilisateur: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly utilisateur: {
      readonly est_actif: CodecTypes['pg/bool@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly matricule: CodecTypes['pg/text@1']['input'] | null;
      readonly mot_de_passe: CodecTypes['pg/text@1']['input'] | null;
      readonly nom: CodecTypes['pg/text@1']['input'] | null;
      readonly prenom: CodecTypes['pg/text@1']['input'] | null;
      readonly role: ReadonlyArray<'agent' | 'admin' | 'superviseur'>;
    };
    readonly vehicule: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_personnel: CodecTypes['pg/int4@1']['input'] | null;
      readonly numero_plaque: CodecTypes['pg/text@1']['input'] | null;
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly agent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id_utilisateur: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['id_utilisateur'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agent';
                    readonly columns: readonly ['id_utilisateur'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'utilisateur';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly mouvement: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id_vehicule: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly heure_arrivee: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly heure_depart: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly id_agent: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly statut: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly observation: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'mouvement_id_vehicule_idx_0338d4ea';
                  readonly prefix: 'mouvement_id_vehicule_idx';
                  readonly columns: readonly ['id_vehicule'];
                  readonly unique: false;
                },
                {
                  readonly name: 'mouvement_id_agent_idx_a3cd4e63';
                  readonly prefix: 'mouvement_id_agent_idx';
                  readonly columns: readonly ['id_agent'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'mouvement';
                    readonly columns: readonly ['id_vehicule'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'vehicule';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'mouvement';
                    readonly columns: readonly ['id_agent'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agent';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly personnel: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id_utilisateur: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly fonction: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['id_utilisateur'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'personnel';
                    readonly columns: readonly ['id_utilisateur'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'utilisateur';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly utilisateur: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly nom: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly prenom: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly matricule: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly mot_de_passe: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly est_actif: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['matricule'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly vehicule: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly numero_plaque: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id_personnel: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'vehicule_id_personnel_idx_a5410273';
                  readonly prefix: 'vehicule_id_personnel_idx';
                  readonly columns: readonly ['id_personnel'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'vehicule';
                    readonly columns: readonly ['id_personnel'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'personnel';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly FonctionEnum: {
              readonly kind: 'valueSet';
              readonly values: readonly ['DGASJ', 'DGCC', 'DGCP'];
            };
            readonly RoleEnum: {
              readonly kind: 'valueSet';
              readonly values: readonly ['agent', 'admin', 'superviseur'];
            };
            readonly StatutEnum: {
              readonly kind: 'valueSet';
              readonly values: readonly ['sur_site', 'hors_site'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly utilisateur: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Utilisateur';
    };
    readonly personnel: { readonly namespace: 'public' & NamespaceId; readonly model: 'Personnel' };
    readonly agent: { readonly namespace: 'public' & NamespaceId; readonly model: 'Agent' };
    readonly vehicule: { readonly namespace: 'public' & NamespaceId; readonly model: 'Vehicule' };
    readonly mouvement: { readonly namespace: 'public' & NamespaceId; readonly model: 'Mouvement' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Agent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_utilisateur: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly mouvements: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Mouvement';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['id_agent'];
                };
              };
              readonly utilisateur: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Utilisateur';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['id_utilisateur'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'agent';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly id_utilisateur: { readonly column: 'id_utilisateur' };
              };
            };
          };
          readonly Mouvement: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_vehicule: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly heure_arrivee: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly heure_depart: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id_agent: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly statut: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly observation: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly agent: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Agent';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['id_agent'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly vehicule: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Vehicule';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['id_vehicule'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'mouvement';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly id_vehicule: { readonly column: 'id_vehicule' };
                readonly heure_arrivee: { readonly column: 'heure_arrivee' };
                readonly heure_depart: { readonly column: 'heure_depart' };
                readonly id_agent: { readonly column: 'id_agent' };
                readonly statut: { readonly column: 'statut' };
                readonly observation: { readonly column: 'observation' };
              };
            };
          };
          readonly Personnel: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_utilisateur: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly fonction: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
            };
            readonly relations: {
              readonly utilisateur: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Utilisateur';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['id_utilisateur'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly vehicules: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Vehicule';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['id_personnel'];
                };
              };
            };
            readonly storage: {
              readonly table: 'personnel';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly id_utilisateur: { readonly column: 'id_utilisateur' };
                readonly fonction: { readonly column: 'fonction' };
              };
            };
          };
          readonly Utilisateur: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nom: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly prenom: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly matricule: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly mot_de_passe: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly est_actif: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly agent: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Agent';
                };
                readonly cardinality: '1:1';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['id_utilisateur'];
                };
              };
              readonly personnel: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Personnel';
                };
                readonly cardinality: '1:1';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['id_utilisateur'];
                };
              };
            };
            readonly storage: {
              readonly table: 'utilisateur';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nom: { readonly column: 'nom' };
                readonly prenom: { readonly column: 'prenom' };
                readonly matricule: { readonly column: 'matricule' };
                readonly mot_de_passe: { readonly column: 'mot_de_passe' };
                readonly role: { readonly column: 'role' };
                readonly est_actif: { readonly column: 'est_actif' };
              };
            };
          };
          readonly Vehicule: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly numero_plaque: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id_personnel: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly mouvements: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Mouvement';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['id_vehicule'];
                };
              };
              readonly personnel: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Personnel';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['id_personnel'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'vehicule';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly numero_plaque: { readonly column: 'numero_plaque' };
                readonly id_personnel: { readonly column: 'id_personnel' };
              };
            };
          };
        };
        readonly enum: {
          readonly RoleEnum: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'agent'; readonly value: 'agent' },
              { readonly name: 'admin'; readonly value: 'admin' },
              { readonly name: 'superviseur'; readonly value: 'superviseur' },
            ];
          };
          readonly FonctionEnum: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'DGASJ'; readonly value: 'DGASJ' },
              { readonly name: 'DGCC'; readonly value: 'DGCC' },
              { readonly name: 'DGCP'; readonly value: 'DGCP' },
            ];
          };
          readonly StatutEnum: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'sur_site'; readonly value: 'sur_site' },
              { readonly name: 'hors_site'; readonly value: 'hors_site' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
